# Galician translation for duplicity
# Copyright (c) 2013 Rosetta Contributors and Canonical Ltd 2013
# This file is distributed under the same license as the duplicity package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2013.
#
msgid ""
msgstr ""
"Project-Id-Version: duplicity\n"
"Report-Msgid-Bugs-To: Kenneth Loafman <kenneth@loafman.com>\n"
"POT-Creation-Date: 2019-07-13 14:09-0500\n"
"PO-Revision-Date: 2018-02-23 13:10+0000\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: Galician <gl@li.org>\n"
"Language: gl\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=n != 1;\n"
"X-Launchpad-Export-Date: 2019-07-13 06:01+0000\n"
"X-Generator: Launchpad (build 19007)\n"

#: ../bin/duplicity:133
msgid "Reuse configured PASSPHRASE as SIGN_PASSPHRASE"
msgstr "Rexeitar configurar PASSPHRASE como SIGN_PASSPHRASE"

#: ../bin/duplicity:140
msgid "Reuse configured SIGN_PASSPHRASE as PASSPHRASE"
msgstr "Rexeitar configurar SIGN_PASSPHRASE como PASSPHRASE"

#: ../bin/duplicity:179
msgid "PASSPHRASE variable not set, asking user."
msgstr "Variábel PASSPHRASE non estabelecida, preguntar ao usuario."

#: ../bin/duplicity:194
msgid "GnuPG passphrase for signing key:"
msgstr "Frase de paso GnuPG para chave de asinado:"

#: ../bin/duplicity:199
msgid "GnuPG passphrase:"
msgstr "Frase de paso de GnuPG:"

#: ../bin/duplicity:204
msgid "Retype passphrase for signing key to confirm: "
msgstr "Volva a teclear a frase de paso da chave de asinado para confirmar: "

#: ../bin/duplicity:206
msgid "Retype passphrase to confirm: "
msgstr "Reescriba a frase de paso para confirmar: "

#: ../bin/duplicity:209
msgid "First and second passphrases do not match!  Please try again."
msgstr "A primeira e a segunda non coinciden! Por favor ténteo de novo."

#: ../bin/duplicity:216
msgid ""
"Cannot use empty passphrase with symmetric encryption!  Please try again."
msgstr ""
"Non pode usar unha frase de paso en branco con cifrado asimétrico! Por favor "
"ténteo de novo."

#: ../bin/duplicity:273
#, python-format
msgid ""
"File %s complete in backup set.\n"
"Continuing restart on file %s."
msgstr ""
"O ficheiro %s está completo no conxunto de repaldo.\n"
"Continuar a restauración no ficheiro %s."

#: ../bin/duplicity:282
#, python-format
msgid ""
"File %s missing in backup set.\n"
"Continuing restart on file %s."
msgstr ""
"O ficheiro %s falta no conxunto de respaldo.\n"
"Continuar o reinicio no ficheiro %s."

#: ../bin/duplicity:331
#, python-format
msgid "File %s was corrupted during upload."
msgstr "O ficheiro %s foi corrompido durante a carga."

#: ../bin/duplicity:364
msgid ""
"Restarting backup, but current encryption settings do not match original "
"settings"
msgstr ""
"Reiniciando copia de respaldo, pero a configuración actual de cifrado non "
"coincide coa configuración orixinal"

#: ../bin/duplicity:387
#, python-format
msgid "Restarting after volume %s, file %s, block %s"
msgstr "Reiníciase após volume %s, ficheiro %s, bloque %s"

#: ../bin/duplicity:457
#, python-format
msgid "Processed volume %d"
msgstr "Procesouse o volume %d"

#: ../bin/duplicity:607
msgid ""
"Fatal Error: Unable to start incremental backup.  Old signatures not found "
"and incremental specified"
msgstr ""
"Erro fatal: non foi posíbel iniciar o respaldo incremental. As sinaturas "
"antigas non se atoparon e especificouse incremental"

#: ../bin/duplicity:611
msgid "No signatures found, switching to full backup."
msgstr "Firmas non atopadas, cambiando a un respaldo completo."

#: ../bin/duplicity:625
msgid "Backup Statistics"
msgstr "Estatísticas do respaldo"

#: ../bin/duplicity:731
#, python-format
msgid "%s not found in archive - no files restored."
msgstr ""
"Non foi posíbel atopar %s no arquivo - non se restaurou ningún ficheiro."

#: ../bin/duplicity:735
msgid "No files found in archive - nothing restored."
msgstr "Non se atoparon ficheiros no arquivo - non se restaurou nada."

#: ../bin/duplicity:768
#, python-format
msgid "Processed volume %d of %d"
msgstr "Volume %d procesado de %d"

#: ../bin/duplicity:802
#, python-format
msgid "Invalid data - %s hash mismatch for file:"
msgstr "datos non válidos - o hash %s non coincide para o ficheiro:"

#: ../bin/duplicity:805
#, python-format
msgid "Calculated hash: %s"
msgstr "Hash calculado: %s"

#: ../bin/duplicity:806
#, python-format
msgid "Manifest hash: %s"
msgstr "Hash do manifesto: %s"

#: ../bin/duplicity:849
#, python-format
msgid "Volume was signed by key %s, not %s"
msgstr "O volume foi asinado pola chave %s, non %s"

#: ../bin/duplicity:881
#, python-format
msgid "Verify complete: %s, %s."
msgstr "Verificación completa> %s, %s."

#: ../bin/duplicity:882
#, python-format
msgid "%d file compared"
msgid_plural "%d files compared"
msgstr[0] "%d ficheiro comparado"
msgstr[1] "%d ficheiros comparados"

#: ../bin/duplicity:884
#, python-format
msgid "%d difference found"
msgid_plural "%d differences found"
msgstr[0] "%d diferenza atopada"
msgstr[1] "%d diferenzas atopadas"

#: ../bin/duplicity:903
msgid "No extraneous files found, nothing deleted in cleanup."
msgstr "Non se atopou ningún ficheiro raro, non se borrou nada na limpeza."

#: ../bin/duplicity:908
msgid "Deleting this file from backend:"
msgid_plural "Deleting these files from backend:"
msgstr[0] "Eliminando este ficheiro desde o motor:"
msgstr[1] "Eliminando estes ficheiros desde o motor:"

#: ../bin/duplicity:919
msgid "Found the following file to delete:"
msgid_plural "Found the following files to delete:"
msgstr[0] "Atopouse o seguinte ficheiro para eliminar:"
msgstr[1] "Atopáronse os seguintes ficheiros para eliminar:"

#: ../bin/duplicity:922
msgid "Run duplicity again with the --force option to actually delete."
msgstr "Execute duplicity de novo coa opción --force para eliminar realmente."

#: ../bin/duplicity:965
msgid "There are backup set(s) at time(s):"
msgstr "Hai conxuntos de respaldo con hora:"

#: ../bin/duplicity:967
msgid "Which can't be deleted because newer sets depend on them."
msgstr "Que non se poden eliminar porque os novos conxuntos dependen deles."

#: ../bin/duplicity:971
msgid ""
"Current active backup chain is older than specified time.  However, it will "
"not be deleted.  To remove all your backups, manually purge the repository."
msgstr ""
"A cadea de respaldo activa é máis antiga que a hora especificada, polo que "
"non se eliminará. Para eliminar todos os seus respaldos, purgue manualmente "
"o repositorio."

#: ../bin/duplicity:984
msgid "No old backup sets found, nothing deleted."
msgstr "Non se atoparon respaldos, nada que eliminar."

#: ../bin/duplicity:987
msgid "Deleting backup chain at time:"
msgid_plural "Deleting backup chains at times:"
msgstr[0] ""
msgstr[1] ""

#: ../bin/duplicity:999
#, python-format
msgid "Deleting any incremental signature chain rooted at %s"
msgstr ""

#: ../bin/duplicity:1001
#, python-format
msgid "Deleting any incremental backup chain rooted at %s"
msgstr ""

#: ../bin/duplicity:1004
#, python-format
msgid "Deleting complete signature chain %s"
msgstr ""

#: ../bin/duplicity:1006
#, python-format
msgid "Deleting complete backup chain %s"
msgstr ""

#: ../bin/duplicity:1012
msgid "Found old backup chain at the following time:"
msgid_plural "Found old backup chains at the following times:"
msgstr[0] ""
msgstr[1] ""

#: ../bin/duplicity:1016
msgid "Rerun command with --force option to actually delete."
msgstr "Execute de novo a orde coa opción --force para eliminar realmente."

#: ../bin/duplicity:1039
msgid "No old backup sets found."
msgstr ""

#: ../bin/duplicity:1054
#, python-format
msgid "Signature %s already replicated"
msgstr ""

#: ../bin/duplicity:1061 ../bin/duplicity:1100
#, python-format
msgid "Replicating %s."
msgstr ""

#: ../bin/duplicity:1088
#, python-format
msgid "Backupset %s already replicated"
msgstr ""

#: ../bin/duplicity:1236
#, python-format
msgid "Deleting local %s (not authoritative at backend)."
msgstr "Eliminando localmente %s (non autoritativo no motor)"

#: ../bin/duplicity:1241
#, python-format
msgid "Unable to delete %s: %s"
msgstr "Non se pode eliminar %s: %s"

#: ../bin/duplicity:1275 ../duplicity/dup_temp.py:267
#, python-format
msgid "Failed to read %s: %s"
msgstr "Produciuse un fallo ao ler %s: %s"

#: ../bin/duplicity:1289
#, python-format
msgid "Copying %s to local cache."
msgstr "Copiando %s na caché local."

#: ../bin/duplicity:1337
msgid "Local and Remote metadata are synchronized, no sync needed."
msgstr ""
"Os metadatos en local e remoto están sincronizados, non é preciso "
"sincronizar."

#: ../bin/duplicity:1342
msgid "Synchronizing remote metadata to local cache..."
msgstr "Sincronizando metadatos remotos coa caché local..."

#: ../bin/duplicity:1355
msgid "Sync would copy the following from remote to local:"
msgstr "A sincronización copiaría o seguinte de remoto a local:"

#: ../bin/duplicity:1358
msgid "Sync would remove the following spurious local files:"
msgstr "A sincronización eliminaría os seguintes ficheiros locais falsos:"

#: ../bin/duplicity:1402
msgid "Unable to get free space on temp."
msgstr "Non foi posíbel obter espazo libre en temp."

#: ../bin/duplicity:1410
#, python-format
msgid "Temp space has %d available, backup needs approx %d."
msgstr ""
"O espazo temporal ten %d dispoñíbel, a copia de respaldo precisa "
"aproximadamente %d."

#: ../bin/duplicity:1413
#, python-format
msgid "Temp has %d available, backup will use approx %d."
msgstr ""
"O espazo temporal ten %d dispoñíbel, o respaldo usará aproximadamente %d."

#: ../bin/duplicity:1421
msgid "Unable to get max open files."
msgstr "Non é posíbel obter o máximo de ficheiros abertos."

#: ../bin/duplicity:1425
#, python-format
msgid ""
"Max open files of %s is too low, should be >= 1024.\n"
"Use 'ulimit -n 1024' or higher to correct.\n"
msgstr ""
"O máximo de ficheiros abertos %s é demasiado pequeno, debería ser >= 1024.\n"
"Empregue «ulimit -n 1024» ou máis alto para corrixilo.\n"

#: ../bin/duplicity:1477
msgid ""
"RESTART: The first volume failed to upload before termination.\n"
"         Restart is impossible...starting backup from beginning."
msgstr ""
"REINICIAR: O primeiro volume non se cargou antes da terminación.\n"
"Reiniciar é imposíbel... iniciando respaldo desde o principio."

#: ../bin/duplicity:1483
#, python-format
msgid ""
"RESTART: Volumes %d to %d failed to upload before termination.\n"
"         Restarting backup at volume %d."
msgstr ""
"REINICIAR: Volúmenes %d a %d fallaron ao cargar antes de terminar.\n"
"         Reiniciar copia de respaldo no volume %d."

#: ../bin/duplicity:1490
#, python-format
msgid ""
"RESTART: Impossible backup state: manifest has %d vols, remote has %d vols.\n"
"         Restart is impossible ... duplicity will clean off the last "
"partial\n"
"         backup then restart the backup from the beginning."
msgstr ""
"REINICIAR: Estado de copia de respaldo non posíbel: o manifesto ten %d vols, "
"o remotor ten %d vols.\n"
"         Non é posíbel reiniciar .. duplicity limpiará a última copia de "
"respaldo parcial\n"
"         e reiniciará a copia desde o principio."

#: ../bin/duplicity:1511
msgid ""
"\n"
"PYTHONOPTIMIZE in the environment causes duplicity to fail to\n"
"recognize its own backups.  Please remove PYTHONOPTIMIZE from\n"
"the environment and rerun the backup.\n"
"\n"
"See https://bugs.launchpad.net/duplicity/+bug/931175\n"
msgstr ""
"\n"
"PYTHONOPTIMIZE no ambiente provoca que duplicity non recoñeza\n"
"as súas propias copias de seguranza. Retire PYTHONOPTIMIZE\n"
"do ambiente e execute a copia de seguranza de novo.\n"
"\n"
"Vexa https://bugs.launchpad.net/duplicity/+bug/931175\n"

#: ../bin/duplicity:1534
#, python-format
msgid "Acquiring lockfile %s"
msgstr "A adquirir o ficheiro de bloqueo %s"

#: ../bin/duplicity:1592
#, python-format
msgid "Last %s backup left a partial set, restarting."
msgstr ""
"A última copia de respaldo %s deixou unha configuración parcial, reiniciar."

#: ../bin/duplicity:1596
#, python-format
msgid "Cleaning up previous partial %s backup set, restarting."
msgstr ""

#: ../bin/duplicity:1608
msgid "Last full backup date:"
msgstr "Data da última copia de seguranza completa:"

#: ../bin/duplicity:1610
msgid "Last full backup date: none"
msgstr "Data da última copia de seguranza completa: ningunha"

#: ../bin/duplicity:1613
msgid "Last full backup is too old, forcing full backup"
msgstr ""
"A data da última copia de seguranza completa é demasiado antiga; obrígase a "
"unha copia completa"

#: ../bin/duplicity:1662
msgid ""
"When using symmetric encryption, the signing passphrase must equal the "
"encryption passphrase."
msgstr ""
"Ao empregar cifrado simétrico a frase de paso da sinatura ha de ser igual á "
"frase de paso de cifrado."

#: ../bin/duplicity:1731
msgid "INT intercepted...exiting."
msgstr ""

#: ../bin/duplicity:1739
#, python-format
msgid "GPG error detail: %s"
msgstr "Detalle do erro de GPG: %s"

#: ../bin/duplicity:1749
#, python-format
msgid "User error detail: %s"
msgstr "Detalle do erro do usuario: %s"

#: ../bin/duplicity:1759
#, python-format
msgid "Backend error detail: %s"
msgstr "Detalle do erro da infraestrutura: %s"

#: ../bin/rdiffdir:63 ../duplicity/commandline.py:268
#, python-format
msgid "Error opening file %s"
msgstr "Produciuse un erro ao abrir o ficheiro %s"

#: ../bin/rdiffdir:130
#, python-format
msgid "File %s already exists, will not overwrite."
msgstr "O ficheiro %s xa existe; non será substituído."

#: ../duplicity/asyncscheduler.py:71
#, python-format
msgid "instantiating at concurrency %d"
msgstr "crear unha instancia na concurrencia %d"

#: ../duplicity/asyncscheduler.py:98
msgid "inserting barrier"
msgstr "insertando barreira"

#: ../duplicity/asyncscheduler.py:147
msgid "running task synchronously (asynchronicity disabled)"
msgstr "execución de tarefa de forma síncrona (asíncronía desactivada)"

#: ../duplicity/asyncscheduler.py:153
msgid "scheduling task for asynchronous execution"
msgstr "programación de tarefas para a execución asíncrona"

#: ../duplicity/asyncscheduler.py:182
msgid "task completed successfully"
msgstr "tarefa completada correctamente"

#: ../duplicity/asyncscheduler.py:193
msgid ""
"a previously scheduled task has failed; propagating the result immediately"
msgstr ""
"unha tarefa planificada previamente fallou; propagando o resultado "
"inmediatamente"

#: ../duplicity/asyncscheduler.py:216 ../duplicity/asyncscheduler.py:237
#, python-format
msgid "active workers = %d"
msgstr "traballadores activos = %d"

#: ../duplicity/asyncscheduler.py:257
#, python-format
msgid "task execution done (success: %s)"
msgstr "execución da tarefa realizada (éxito: %s)"

#: ../duplicity/backend.py:108
#, python-format
msgid "Import of %s %s"
msgstr "Importación de %s %s"

#: ../duplicity/backend.py:217
#, python-format
msgid "Could not initialize backend: %s"
msgstr "Non foi posíbel inicializar a infraestrutura: %s"

#: ../duplicity/backend.py:381
#, python-format
msgid "Backtrace of previous error: %s"
msgstr "Trazado inverso do erro anterior: %s"

#: ../duplicity/backend.py:396
#, python-format
msgid "Giving up after %s attempts. %s: %s"
msgstr "Abandónase despois de %s intentos. %s: %s"

#: ../duplicity/backend.py:400
#, python-format
msgid "Attempt %s failed. %s: %s"
msgstr "Fallou o intento %s. %s: %s"

#: ../duplicity/backend.py:494
#, python-format
msgid "Reading results of '%s'"
msgstr "Lendo resultados de «%s»"

#: ../duplicity/backend.py:520
#, python-format
msgid "Writing %s"
msgstr "Escribindo %s"

#: ../duplicity/backend.py:561
#, python-format
msgid "File %s not found locally after get from backend"
msgstr ""

#: ../duplicity/backends/giobackend.py:108
#, python-format
msgid "Connection failed, please check your password: %s"
msgstr "Fallou a conexión; comprobe o contrasinal: %s"

#: ../duplicity/backends/multibackend.py:89
#, python-format
msgid "MultiBackend: Could not parse query string %s: %s "
msgstr ""

#: ../duplicity/backends/multibackend.py:98
#, python-format
msgid "MultiBackend: Invalid query string %s: more than one value for %s"
msgstr ""

#: ../duplicity/backends/multibackend.py:103
#, python-format
msgid "MultiBackend: Invalid query string %s: unknown parameter %s"
msgstr ""

#: ../duplicity/backends/multibackend.py:153
#: ../duplicity/backends/multibackend.py:158
#, python-format
msgid "MultiBackend: illegal value for %s: %s"
msgstr ""

#: ../duplicity/backends/multibackend.py:166
#, python-format
msgid "MultiBackend: Url %s"
msgstr ""

#: ../duplicity/backends/multibackend.py:170
#, python-format
msgid "MultiBackend: Could not load config file %s: %s "
msgstr ""

#: ../duplicity/backends/multibackend.py:179
#, python-format
msgid "MultiBackend: use store %s"
msgstr ""

#: ../duplicity/backends/multibackend.py:184
#, python-format
msgid "MultiBackend: set env %s = %s"
msgstr ""

#: ../duplicity/backends/multibackend.py:197
#, python-format
msgid "Multibackend: register affinity for prefix %s"
msgstr ""

#: ../duplicity/backends/multibackend.py:238
#, python-format
msgid "MultiBackend: _put: write to store #%s (%s)"
msgstr ""

#: ../duplicity/backends/multibackend.py:251
#, python-format
msgid "MultiBackend: failed to write to store #%s (%s), try #%s, Exception: %s"
msgstr ""

#: ../duplicity/backends/multibackend.py:258
#, python-format
msgid "MultiBackend: failed to write %s. Aborting process."
msgstr ""

#: ../duplicity/backends/multibackend.py:265
#, python-format
msgid ""
"MultiBackend: failed to write %s. Tried all backing stores and none succeeded"
msgstr ""

#: ../duplicity/backends/multibackend.py:284
#, python-format
msgid "MultiBackend: failed to get %s to %s from %s"
msgstr ""

#: ../duplicity/backends/multibackend.py:287
#, python-format
msgid ""
"MultiBackend: failed to get %s. Tried all backing stores and none succeeded"
msgstr ""

#: ../duplicity/backends/multibackend.py:296
#, python-format
msgid "MultiBackend: list from %s: %s"
msgstr ""

#: ../duplicity/backends/multibackend.py:302
#, python-format
msgid "MultiBackend: combined list: %s"
msgstr ""

#: ../duplicity/backends/multibackend.py:327
#, python-format
msgid "MultiBackend: failed to delete %s from %s"
msgstr ""

#: ../duplicity/backends/multibackend.py:331
#, python-format
msgid ""
"MultiBackend: failed to delete %s. Tried all backing stores and none "
"succeeded"
msgstr ""

#: ../duplicity/backends/pydrivebackend.py:150
#, python-format
msgid "PyDrive backend: multiple files called '%s'."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:66
msgid "Missing socket or ssl python modules."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:84
#, python-format
msgid "Cacert database file '%s' is not readable."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:105
msgid ""
"Option '--ssl-cacert-path' is not supported with python 2.7.8 and below."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:109
#, python-format
msgid ""
"For certificate verification with python 2.7.8 or earlier a cacert database\n"
"file is needed in one of these locations: %s\n"
"Hints:\n"
"Consult the man page, chapter 'SSL Certificate Verification'.\n"
"Consider using the options --ssl-cacert-file, --ssl-no-check-certificate ."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:155
#, python-format
msgid "Using WebDAV protocol %s"
msgstr ""

#: ../duplicity/backends/webdavbackend.py:156
#, python-format
msgid "Using WebDAV host %s port %s"
msgstr ""

#: ../duplicity/backends/webdavbackend.py:158
#, python-format
msgid "Using WebDAV directory %s"
msgstr ""

#: ../duplicity/backends/webdavbackend.py:189
#, python-format
msgid "WebDAV create connection on '%s'"
msgstr ""

#: ../duplicity/backends/webdavbackend.py:200
#, python-format
msgid "WebDAV Unknown URI scheme: %s"
msgstr ""

#: ../duplicity/backends/webdavbackend.py:219
#, python-format
msgid "WebDAV %s %s request with headers: %s "
msgstr ""

#: ../duplicity/backends/webdavbackend.py:220
#: ../duplicity/backends/webdavbackend.py:243
#, python-format
msgid "WebDAV data length: %s "
msgstr ""

#: ../duplicity/backends/webdavbackend.py:223
#, python-format
msgid "WebDAV response status %s with reason '%s'."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:229
#, python-format
msgid "WebDAV redirect to: %s "
msgstr ""

#: ../duplicity/backends/webdavbackend.py:231
msgid "WebDAV redirected 10 times. Giving up."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:236
msgid "WebDAV missing location header in redirect response."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:241
msgid "WebDAV retry request with authentification headers."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:242
#, python-format
msgid "WebDAV %s %s request2 with headers: %s "
msgstr ""

#: ../duplicity/backends/webdavbackend.py:246
#, python-format
msgid "WebDAV response2 status %s with reason '%s'."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:263
msgid ""
"python-kerberos needed to use kerberos                           "
"authorization, falling back to basic auth."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:267
#, python-format
msgid ""
"Kerberos authorization failed: %s.                          Falling back to "
"basic auth."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:365
#, python-format
msgid "Creating missing directory %s"
msgstr ""

#: ../duplicity/backends/webdavbackend.py:369
#, python-format
msgid "WebDAV MKCOL %s failed: %s %s"
msgstr ""

#: ../duplicity/backends/webdavbackend.py:382
#, python-format
msgid "WebDAV path decoding and translation: %s -> %s"
msgstr ""

#: ../duplicity/backends/webdavbackend.py:427
#, python-format
msgid "WebDAV GET Bad status code %s reason %s."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:449
#, python-format
msgid "WebDAV PUT Bad status code %s reason %s."
msgstr ""

#: ../duplicity/backends/webdavbackend.py:469
#, python-format
msgid "WebDAV DEL Bad status code %s reason %s."
msgstr ""

#: ../duplicity/commandline.py:77
#, python-format
msgid ""
"Warning: Option %s is pending deprecation and will be removed in a future "
"release.\n"
"Use of default filenames is strongly suggested."
msgstr ""

#: ../duplicity/commandline.py:84
#, python-format
msgid ""
"Warning: Option %s is pending deprecation and will be removed in a future "
"release.\n"
"--include-filelist and --exclude-filelist now accept globbing characters and "
"should be used instead."
msgstr ""

#: ../duplicity/commandline.py:94
#, python-format
msgid ""
"Warning: Option %s is pending deprecation and will be removed in a future "
"release.\n"
"On many GNU/Linux systems, stdin is represented by /dev/stdin and\n"
"--include-filelist=/dev/stdin or --exclude-filelist=/dev/stdin could\n"
"be used as a substitute."
msgstr ""

#. Used in usage help to represent a Unix-style path name. Example:
#. --archive-dir <path>
#: ../duplicity/commandline.py:289 ../duplicity/commandline.py:299
#: ../duplicity/commandline.py:320 ../duplicity/commandline.py:394
#: ../duplicity/commandline.py:412 ../duplicity/commandline.py:641
#: ../duplicity/commandline.py:674 ../duplicity/commandline.py:873
msgid "path"
msgstr "ruta"

#. Used in usage help to represent an ID for a GnuPG key. Example:
#. --encrypt-key <gpg_key_id>
#. Used in usage help to represent an ID for a hidden GnuPG key. Example:
#. --hidden-encrypt-key <gpg_key_id>
#. Used in usage help to represent an ID for a GnuPG key. Example:
#. --encrypt-key <gpg_key_id>
#: ../duplicity/commandline.py:315 ../duplicity/commandline.py:322
#: ../duplicity/commandline.py:418 ../duplicity/commandline.py:625
#: ../duplicity/commandline.py:846
msgid "gpg-key-id"
msgstr "identificador-chave-gpg"

#. Used in usage help to represent a "glob" style pattern for
#. matching one or more files, as described in the documentation.
#. Example:
#. --exclude <shell_pattern>
#: ../duplicity/commandline.py:330 ../duplicity/commandline.py:443
#: ../duplicity/commandline.py:896
msgid "shell_pattern"
msgstr "padrón_de_consola"

#. Used in usage help to represent the name of a file. Example:
#. --log-file <filename>
#: ../duplicity/commandline.py:336 ../duplicity/commandline.py:345
#: ../duplicity/commandline.py:352 ../duplicity/commandline.py:445
#: ../duplicity/commandline.py:452 ../duplicity/commandline.py:465
#: ../duplicity/commandline.py:842
msgid "filename"
msgstr "nome de ficheiro"

#. Used in usage help to represent a regular expression (regexp).
#: ../duplicity/commandline.py:359 ../duplicity/commandline.py:456
msgid "regular_expression"
msgstr "expresión_regular"

#. Used in usage help to represent a time spec for a previous
#. point in time, as described in the documentation. Example:
#. duplicity remove-older-than time [options] target_url
#: ../duplicity/commandline.py:363 ../duplicity/commandline.py:406
#: ../duplicity/commandline.py:532 ../duplicity/commandline.py:928
msgid "time"
msgstr "hora"

#. Used in usage help. (Should be consistent with the "Options:"
#. header.) Example:
#. duplicity [full|incremental] [options] source_dir target_url
#: ../duplicity/commandline.py:414 ../duplicity/commandline.py:512
#: ../duplicity/commandline.py:535 ../duplicity/commandline.py:633
#: ../duplicity/commandline.py:861
msgid "options"
msgstr "opcións"

#: ../duplicity/commandline.py:429
#, python-format
msgid ""
"Running in 'ignore errors' mode due to %s; please re-consider if this was "
"not intended"
msgstr ""
"A executar o modo «ignorar erros» debido a %s; reconsidere se isto non era o "
"que pretendía"

#. Used in usage help to represent an imap mailbox
#: ../duplicity/commandline.py:441
msgid "imap_mailbox"
msgstr "caixa_correo_imap"

#: ../duplicity/commandline.py:459
msgid "file_descriptor"
msgstr "descritor_de_ficheiro"

#. Used in usage help to represent a desired number of
#. something. Example:
#. --num-retries <number>
#: ../duplicity/commandline.py:470 ../duplicity/commandline.py:492
#: ../duplicity/commandline.py:509 ../duplicity/commandline.py:518
#: ../duplicity/commandline.py:565 ../duplicity/commandline.py:570
#: ../duplicity/commandline.py:574 ../duplicity/commandline.py:593
#: ../duplicity/commandline.py:599 ../duplicity/commandline.py:603
#: ../duplicity/commandline.py:669 ../duplicity/commandline.py:856
msgid "number"
msgstr "número"

#. Used in usage help (noun)
#: ../duplicity/commandline.py:473
msgid "backup name"
msgstr "nome de copia de seguranza"

#: ../duplicity/commandline.py:588
msgid "policy"
msgstr ""

#: ../duplicity/commandline.py:606
msgid "Hot|Cool|Archive"
msgstr ""

#. noun
#: ../duplicity/commandline.py:609 ../duplicity/commandline.py:612
#: ../duplicity/commandline.py:827
msgid "command"
msgstr "orde"

#: ../duplicity/commandline.py:615
msgid "pyrax|cloudfiles"
msgstr ""

#: ../duplicity/commandline.py:636
msgid "pem formatted bundle of certificate authorities"
msgstr ""

#: ../duplicity/commandline.py:637
msgid "path to a folder with certificate authority files"
msgstr "ruta a un cartafol con ficheiros de autoridade de certificación"

#. Used in usage help. Example:
#. --timeout <seconds>
#. Used in usage help. Example:
#. --backend-retry-delay <seconds>
#. Used in usage help. Example:
#. --timeout <seconds>
#: ../duplicity/commandline.py:646 ../duplicity/commandline.py:680
#: ../duplicity/commandline.py:890
msgid "seconds"
msgstr "segundos"

#. abbreviation for "character" (noun)
#: ../duplicity/commandline.py:652 ../duplicity/commandline.py:824
msgid "char"
msgstr "carácter"

#: ../duplicity/commandline.py:790
#, python-format
msgid "Using archive dir: %s"
msgstr "Emprégase o directorio de arquivado: %s"

#: ../duplicity/commandline.py:791
#, python-format
msgid "Using backup name: %s"
msgstr "Emprégase o nome de copia de seguranza: %s"

#: ../duplicity/commandline.py:798
#, python-format
msgid "Command line error: %s"
msgstr "Erro da liña de ordes: %s"

#: ../duplicity/commandline.py:799
msgid "Enter 'duplicity --help' for help screen."
msgstr "Escriba «duplicity --help» para ter unha pantalla de axuda."

#. Used in usage help to represent a Unix-style path name. Example:
#. rsync://user[:password]@other_host[:port]//absolute_path
#: ../duplicity/commandline.py:812
msgid "absolute_path"
msgstr "ruta_absoluta"

#. Used in usage help. Example:
#. tahoe://alias/some_dir
#: ../duplicity/commandline.py:816
msgid "alias"
msgstr "alcume"

#. Used in help to represent a "bucket name" for Amazon Web
#. Services' Simple Storage Service (S3). Example:
#. s3://other.host/bucket_name[/prefix]
#: ../duplicity/commandline.py:821
msgid "bucket_name"
msgstr ""

#. Used in usage help to represent the name of a container in
#. Amazon Web Services' Cloudfront. Example:
#. cf+http://container_name
#: ../duplicity/commandline.py:832
msgid "container_name"
msgstr "nome_de_contedor"

#. noun
#: ../duplicity/commandline.py:835
msgid "count"
msgstr "número"

#. Used in usage help to represent the name of a file directory
#: ../duplicity/commandline.py:838
msgid "directory"
msgstr "directorio"

#. Used in usage help, e.g. to represent the name of a code
#. module. Example:
#. rsync://user[:password]@other.host[:port]::/module/some_dir
#: ../duplicity/commandline.py:851
msgid "module"
msgstr "módulo"

#. Used in usage help to represent an internet hostname. Example:
#. ftp://user[:password]@other.host[:port]/some_dir
#: ../duplicity/commandline.py:865
msgid "other.host"
msgstr "outro.servidor"

#. Used in usage help. Example:
#. ftp://user[:password]@other.host[:port]/some_dir
#: ../duplicity/commandline.py:869
msgid "password"
msgstr "contrasinal"

#. Used in usage help to represent a TCP port number. Example:
#. ftp://user[:password]@other.host[:port]/some_dir
#: ../duplicity/commandline.py:877
msgid "port"
msgstr "porto"

#. Used in usage help. This represents a string to be used as a
#. prefix to names for backup files created by Duplicity. Example:
#. s3://other.host/bucket_name[/prefix]
#: ../duplicity/commandline.py:882
msgid "prefix"
msgstr "prefixo"

#. Used in usage help to represent a Unix-style path name. Example:
#. rsync://user[:password]@other.host[:port]/relative_path
#: ../duplicity/commandline.py:886
msgid "relative_path"
msgstr "ruta_relativa"

#. Used in usage help to represent the name of a single file
#. directory or a Unix-style path to a directory. Example:
#. file:///some_dir
#: ../duplicity/commandline.py:901
msgid "some_dir"
msgstr "un_directorio"

#. Used in usage help to represent the name of a single file
#. directory or a Unix-style path to a directory where files will be
#. coming FROM. Example:
#. duplicity [full|incremental] [options] source_dir target_url
#: ../duplicity/commandline.py:907
msgid "source_dir"
msgstr "directorio_orixe"

#. Used in usage help to represent a URL files will be coming
#. FROM. Example:
#. duplicity [restore] [options] source_url target_dir
#: ../duplicity/commandline.py:912
msgid "source_url"
msgstr "url_destino"

#. Used in usage help to represent the name of a single file
#. directory or a Unix-style path to a directory. where files will be
#. going TO. Example:
#. duplicity [restore] [options] source_url target_dir
#: ../duplicity/commandline.py:918
msgid "target_dir"
msgstr "directorio_destino"

#. Used in usage help to represent a URL files will be going TO.
#. Example:
#. duplicity [full|incremental] [options] source_dir target_url
#: ../duplicity/commandline.py:923
msgid "target_url"
msgstr "url_destino"

#. Used in usage help to represent a user name (i.e. login).
#. Example:
#. ftp://user[:password]@other.host[:port]/some_dir
#: ../duplicity/commandline.py:933
msgid "user"
msgstr "usuario"

#. account id for b2. Example: b2://account_id@bucket/
#: ../duplicity/commandline.py:936
msgid "account_id"
msgstr "identificador_de_conta"

#. application_key for b2.
#. Example: b2://account_id:application_key@bucket/
#: ../duplicity/commandline.py:940
msgid "application_key"
msgstr ""

#. Header in usage help
#: ../duplicity/commandline.py:959
msgid "Backends and their URL formats:"
msgstr "Infraestruturas e os seus formatos URL:"

#. Header in usage help
#: ../duplicity/commandline.py:991
msgid "Commands:"
msgstr "Ordes:"

#: ../duplicity/commandline.py:1016
#, python-format
msgid "Specified archive directory '%s' does not exist, or is not a directory"
msgstr "O directorio indicado, «%s», non existe ou non é un directorio"

#: ../duplicity/commandline.py:1025
#, python-format
msgid ""
"Sign key should be an 8, 16 alt. 40 character hex string, like 'AA0E73D2'.\n"
"Received '%s' instead."
msgstr ""

#: ../duplicity/commandline.py:1085
#, python-format
msgid ""
"Restore destination directory %s already exists.\n"
"Will not overwrite."
msgstr ""
"O directorio de destino da restauración %s xa existe.\n"
"Non se vai substituír."

#: ../duplicity/commandline.py:1090
#, python-format
msgid "Verify directory %s does not exist"
msgstr "Comprobe que o directorio %s non existe"

#: ../duplicity/commandline.py:1096
#, python-format
msgid "Backup source directory %s does not exist."
msgstr "O directorio de orixe da copia de seguranza %s non existe."

#: ../duplicity/commandline.py:1127
#, python-format
msgid "Command line warning: %s"
msgstr "Advertencia da liña de ordes: %s"

#: ../duplicity/commandline.py:1127
msgid ""
"Selection options --exclude/--include\n"
"currently work only when backing up,not restoring."
msgstr ""

#: ../duplicity/commandline.py:1163
#, python-format
msgid "GPG binary is %s, version %s"
msgstr "O binario de GPG é %s, versión %s"

#: ../duplicity/commandline.py:1190
#, python-format
msgid ""
"Bad URL '%s'.\n"
"Examples of URL strings are \"scp://user@host.net:1234/path\" and\n"
"\"file:///usr/local\".  See the man page for more information."
msgstr ""
"O URL «%s» é incorrecto.\n"
"Os exemplos de cadeas de URL inclúen «cp://usuario@servidor.gal:1234/ruta» "
"e\n"
"«file:///usr/local». Vexa a páxina do manual para máis información."

#: ../duplicity/commandline.py:1220
msgid "Main action: "
msgstr "Acción principal: "

#: ../duplicity/diffdir.py:115 ../duplicity/diffdir.py:417
#, python-format
msgid "Error %s getting delta for %s"
msgstr ""

#: ../duplicity/diffdir.py:129
#, python-format
msgid "Getting delta of %s and %s"
msgstr ""

#: ../duplicity/diffdir.py:180
#, python-format
msgid "A %s"
msgstr "A %s"

#: ../duplicity/diffdir.py:187
#, python-format
msgid "M %s"
msgstr "M %s"

#: ../duplicity/diffdir.py:209
#, python-format
msgid "Comparing %s and %s"
msgstr "A comparar %s con %s"

#: ../duplicity/diffdir.py:217
#, python-format
msgid "D %s"
msgstr "D %s"

#: ../duplicity/dup_collections.py:177 ../duplicity/dup_collections.py:191
#, python-format
msgid "BackupSet.delete: missing %s"
msgstr ""

#: ../duplicity/dup_collections.py:216
msgid "Fatal Error: No manifests found for most recent backup"
msgstr "Erro fatal: non se atoparon manifestos para o respaldo máis recente"

#: ../duplicity/dup_collections.py:225
msgid ""
"Fatal Error: Remote manifest does not match local one.  Either the remote "
"backup set or the local archive directory has been corrupted."
msgstr ""
"Erro fatal: o manifesto remoto non coincide co local. Nin a configuración de "
"copia de respaldo remota ou o cartafol do arquivo local están danados."

#: ../duplicity/dup_collections.py:233
msgid "Fatal Error: Neither remote nor local manifest is readable."
msgstr "Erro fatal: nin o manifesto remoto nin o local son lexíbeis."

#: ../duplicity/dup_collections.py:244
#, python-format
msgid "Processing local manifest %s (%s)"
msgstr "A procesar o manifesto local %s (%s)"

#: ../duplicity/dup_collections.py:256
#, python-format
msgid "Error processing remote manifest (%s): %s"
msgstr "Erro ao procesar un manifesto remoto (%s): %s"

#: ../duplicity/dup_collections.py:259
#, python-format
msgid "Processing remote manifest %s (%s)"
msgstr "A procesar un manifesto remoto (%s): %s"

#: ../duplicity/dup_collections.py:355
msgid "Preferring Backupset over previous one!"
msgstr "Prefirir a configuración de copia de respaldo previa"

#: ../duplicity/dup_collections.py:358
#, python-format
msgid "Ignoring incremental Backupset (start_time: %s; needed: %s)"
msgstr ""
"Ignorar a configuración de copia de respaldo incremental (start_time: %s; "
"necesaria: %s)"

#: ../duplicity/dup_collections.py:363
#, python-format
msgid "Added incremental Backupset (start_time: %s / end_time: %s)"
msgstr ""
"Engadida configuración de copia de respaldo incremental (start_time: %s / "
"end_time: %s)"

#: ../duplicity/dup_collections.py:433
msgid "Chain start time: "
msgstr "Hora de inicio da cadea: "

#: ../duplicity/dup_collections.py:434
msgid "Chain end time: "
msgstr "Hora de remate da cadea: "

#: ../duplicity/dup_collections.py:435
#, python-format
msgid "Number of contained backup sets: %d"
msgstr ""

#: ../duplicity/dup_collections.py:437
#, python-format
msgid "Total number of contained volumes: %d"
msgstr "Número total de volumes contidos: %d"

#: ../duplicity/dup_collections.py:439 ../duplicity/dup_collections.py:1235
msgid "Type of backup set:"
msgstr ""

#: ../duplicity/dup_collections.py:439 ../duplicity/dup_collections.py:1235
msgid "Time:"
msgstr "Hora:"

#: ../duplicity/dup_collections.py:439
msgid "Num volumes:"
msgstr "Número de volumes:"

#: ../duplicity/dup_collections.py:443 ../duplicity/dup_collections.py:1241
msgid "Full"
msgstr "Completo"

#: ../duplicity/dup_collections.py:446 ../duplicity/dup_collections.py:1243
msgid "Incremental"
msgstr "Incremental"

#: ../duplicity/dup_collections.py:506
msgid "local"
msgstr "local"

#: ../duplicity/dup_collections.py:508
msgid "remote"
msgstr "remoto"

#: ../duplicity/dup_collections.py:663
msgid "Collection Status"
msgstr "Estado da colección"

#: ../duplicity/dup_collections.py:665
#, python-format
msgid "Connecting with backend: %s"
msgstr "A conectar coa infraestrutura: %s"

#: ../duplicity/dup_collections.py:667
#, python-format
msgid "Archive dir: %s"
msgstr "Directorio dos arquivos: %s"

#: ../duplicity/dup_collections.py:670
#, python-format
msgid "Found %d secondary backup chain."
msgid_plural "Found %d secondary backup chains."
msgstr[0] ""
msgstr[1] ""

#: ../duplicity/dup_collections.py:675
#, python-format
msgid "Secondary chain %d of %d:"
msgstr "Cadea secundaria %d de %d:"

#: ../duplicity/dup_collections.py:681
msgid "Found primary backup chain with matching signature chain:"
msgstr ""

#: ../duplicity/dup_collections.py:685
msgid "No backup chains with active signatures found"
msgstr ""

#: ../duplicity/dup_collections.py:688
#, python-format
msgid "Also found %d backup set not part of any chain,"
msgid_plural "Also found %d backup sets not part of any chain,"
msgstr[0] ""
msgstr[1] ""

#: ../duplicity/dup_collections.py:692
#, python-format
msgid "and %d incomplete backup set."
msgid_plural "and %d incomplete backup sets."
msgstr[0] ""
msgstr[1] ""

#. "cleanup" is a hard-coded command, so do not translate it
#: ../duplicity/dup_collections.py:697
msgid "These may be deleted by running duplicity with the \"cleanup\" command."
msgstr ""

#: ../duplicity/dup_collections.py:700
msgid "No orphaned or incomplete backup sets found."
msgstr ""

#: ../duplicity/dup_collections.py:716
#, python-format
msgid "%d file exists on backend"
msgid_plural "%d files exist on backend"
msgstr[0] "Existe %d ficheiro na infraestrutura"
msgstr[1] "Existen %d ficheiros na infraestrutura"

#: ../duplicity/dup_collections.py:726
#, python-format
msgid "%d file exists in cache"
msgid_plural "%d files exist in cache"
msgstr[0] "Existe %d ficheiro na caché"
msgstr[1] "Existen %d ficheiros na caché"

#: ../duplicity/dup_collections.py:779
msgid "Warning, discarding last backup set, because of missing signature file."
msgstr ""

#: ../duplicity/dup_collections.py:802
msgid "Warning, found the following local orphaned signature file:"
msgid_plural "Warning, found the following local orphaned signature files:"
msgstr[0] ""
msgstr[1] ""

#: ../duplicity/dup_collections.py:811
msgid "Warning, found the following remote orphaned signature file:"
msgid_plural "Warning, found the following remote orphaned signature files:"
msgstr[0] ""
msgstr[1] ""

#: ../duplicity/dup_collections.py:820
msgid "Warning, found signatures but no corresponding backup files"
msgstr ""

#: ../duplicity/dup_collections.py:824
msgid ""
"Warning, found incomplete backup sets, probably left from aborted session"
msgstr ""

#: ../duplicity/dup_collections.py:828
msgid "Warning, found the following orphaned backup file:"
msgid_plural "Warning, found the following orphaned backup files:"
msgstr[0] ""
msgstr[1] ""

#: ../duplicity/dup_collections.py:845
#, python-format
msgid "Extracting backup chains from list of files: %s"
msgstr ""

#: ../duplicity/dup_collections.py:856
#, python-format
msgid "File %s is part of known set"
msgstr "O ficheiro %s fai parte dun conxunto coñecido"

#: ../duplicity/dup_collections.py:859
#, python-format
msgid "File %s is not part of a known set; creating new set"
msgstr ""
"O ficheiro %s non fai parte de ningún conxunto coñecido; créase un conxunto "
"novo"

#: ../duplicity/dup_collections.py:864
#, python-format
msgid "Ignoring file (rejected by backup set) '%s'"
msgstr ""

#: ../duplicity/dup_collections.py:880
#, python-format
msgid "Found backup chain %s"
msgstr ""

#: ../duplicity/dup_collections.py:885
#, python-format
msgid "Added set %s to pre-existing chain %s"
msgstr ""

#: ../duplicity/dup_collections.py:889
#, python-format
msgid "Found orphaned set %s"
msgstr ""

#: ../duplicity/dup_collections.py:1039
#, python-format
msgid ""
"No signature chain for the requested time. Using oldest available chain, "
"starting at time %s."
msgstr ""

#: ../duplicity/dup_collections.py:1233
#, python-format
msgid "File: %s"
msgstr "Ficheiro: %s"

#: ../duplicity/dup_collections.py:1234
#, python-format
msgid "Total number of backup: %d"
msgstr ""

#: ../duplicity/dup_collections.py:1235
msgid "Type of file change:"
msgstr "Tipo de cambio do ficheiro:"

#: ../duplicity/dup_time.py:61
#, python-format
msgid ""
"Bad interval string \"%s\"\n"
"\n"
"Intervals are specified like 2Y (2 years) or 2h30m (2.5 hours).  The\n"
"allowed special characters are s, m, h, D, W, M, and Y.  See the man\n"
"page for more information."
msgstr ""

#: ../duplicity/dup_time.py:67
#, python-format
msgid ""
"Bad time string \"%s\"\n"
"\n"
"The acceptible time strings are intervals (like \"3D64s\"), w3-datetime\n"
"strings, like \"2002-04-26T04:22:01-07:00\" (strings like\n"
"\"2002-04-26T04:22:01\" are also acceptable - duplicity will use the\n"
"current time zone), or ordinary dates like 2/4/1997 or 2001-04-23\n"
"(various combinations are acceptable, but the month always precedes\n"
"the day)."
msgstr ""

#: ../duplicity/gpginterface.py:238
msgid "Threading not available -- zombie processes may appear"
msgstr ""

#: ../duplicity/gpginterface.py:705
#, python-format
msgid "GPG process %d terminated before wait()"
msgstr ""

#: ../duplicity/lazy.py:352
#, python-format
msgid "Warning: oldindex %s >= newindex %s"
msgstr ""

#: ../duplicity/lazy.py:427
#, python-format
msgid "Error '%s' processing %s"
msgstr ""

#: ../duplicity/lazy.py:437
#, python-format
msgid "Skipping %s because of previous error"
msgstr "Omítese %s a causa dun erro anterior"

#: ../duplicity/librsync.py:195
msgid ""
"basis_file must be a (true) file or an object whose file attribute is the "
"underlying true file object"
msgstr ""

#: ../duplicity/manifest.py:96
#, python-format
msgid ""
"Fatal Error: Backup source host has changed.\n"
"Current hostname: %s\n"
"Previous hostname: %s"
msgstr ""

#: ../duplicity/manifest.py:103
#, python-format
msgid ""
"Fatal Error: Backup source directory has changed.\n"
"Current directory: %s\n"
"Previous directory: %s"
msgstr ""

#: ../duplicity/manifest.py:113
msgid ""
"Aborting because you may have accidentally tried to backup two different "
"data sets to the same remote location, or using the same archive directory.  "
"If this is not a mistake, use the --allow-source-mismatch switch to avoid "
"seeing this message"
msgstr ""

#: ../duplicity/manifest.py:215
#, python-format
msgid "Found manifest volume %s"
msgstr ""

#: ../duplicity/manifest.py:222
#, python-format
msgid "Found %s volumes in manifest"
msgstr ""

#: ../duplicity/manifest.py:239
#, python-format
msgid ""
"Manifest file '%s' is corrupt: File count says %d, File list contains %d"
msgstr ""

#: ../duplicity/manifest.py:258
msgid "Manifests not equal because different volume numbers"
msgstr ""

#: ../duplicity/manifest.py:263
msgid "Manifests not equal because volume lists differ"
msgstr ""

#: ../duplicity/manifest.py:268
msgid "Manifests not equal because hosts or directories differ"
msgstr ""

#: ../duplicity/manifest.py:425
msgid "Warning, found extra Volume identifier"
msgstr ""

#: ../duplicity/manifest.py:451
msgid "Other is not VolumeInfo"
msgstr ""

#: ../duplicity/manifest.py:454
msgid "Volume numbers don't match"
msgstr ""

#: ../duplicity/manifest.py:457
msgid "start_indicies don't match"
msgstr ""

#: ../duplicity/manifest.py:460
msgid "end_index don't match"
msgstr ""

#: ../duplicity/manifest.py:467
msgid "Hashes don't match"
msgstr ""

#: ../duplicity/patchdir.py:84 ../duplicity/patchdir.py:89
#, python-format
msgid "Patching %s"
msgstr "A parchear %s"

#: ../duplicity/patchdir.py:550
#, python-format
msgid "Error '%s' patching %s"
msgstr "Erro «%s» ao parchear %s"

#: ../duplicity/patchdir.py:625
#, python-format
msgid "Writing %s of type %s"
msgstr "A escribir %s de tipo %s"

#: ../duplicity/path.py:113
#, python-format
msgid "Warning: %s invalid devnums (0x%X), treating as (0, 0)."
msgstr ""

#: ../duplicity/path.py:242 ../duplicity/path.py:303
#, python-format
msgid "Warning: %s has negative mtime, treating as 0."
msgstr ""

#: ../duplicity/path.py:367
msgid "Difference found:"
msgstr ""

#: ../duplicity/path.py:376
#, python-format
msgid "New file %s"
msgstr ""

#: ../duplicity/path.py:379
#, python-format
msgid "File %s is missing"
msgstr ""

#: ../duplicity/path.py:382
#, python-format
msgid "File %%s has type %s, expected %s"
msgstr ""

#: ../duplicity/path.py:388 ../duplicity/path.py:414
#, python-format
msgid "File %%s has permissions %s, expected %s"
msgstr ""

#: ../duplicity/path.py:393
#, python-format
msgid "File %%s has mtime %s, expected %s"
msgstr ""

#: ../duplicity/path.py:401
#, python-format
msgid "Data for file %s is different"
msgstr ""

#: ../duplicity/path.py:409
#, python-format
msgid "Symlink %%s points to %s, expected %s"
msgstr ""

#: ../duplicity/path.py:418
#, python-format
msgid "Device file %%s has numbers %s, expected %s"
msgstr ""

#: ../duplicity/path.py:600
#, python-format
msgid "Making directory %s"
msgstr ""

#: ../duplicity/path.py:610
#, python-format
msgid "Deleting %s"
msgstr ""

#: ../duplicity/path.py:619
#, python-format
msgid "Touching %s"
msgstr ""

#: ../duplicity/path.py:626
#, python-format
msgid "Deleting tree %s"
msgstr ""

#: ../duplicity/robust.py:64
#, python-format
msgid "Error listing directory %s"
msgstr ""

#: ../duplicity/selection.py:121
#, python-format
msgid "Skipping socket %s"
msgstr ""

#: ../duplicity/selection.py:125
#, python-format
msgid "Error initializing file %s"
msgstr "Produciuse un erro ao inicializar o ficheiro %s"

#: ../duplicity/selection.py:129 ../duplicity/selection.py:154
#: ../duplicity/selection.py:463
#, python-format
msgid "Error accessing possibly locked file %s"
msgstr "Produciuse un erro ao acceder o ficheiro, posibelmente bloqueado, %s"

#: ../duplicity/selection.py:169
#, python-format
msgid "Warning: base %s doesn't exist, continuing"
msgstr "Advertencia: a base %s non existe; continúase"

#: ../duplicity/selection.py:172 ../duplicity/selection.py:190
#: ../duplicity/selection.py:193
#, python-format
msgid "Selecting %s"
msgstr "Seleccionando %s"

#: ../duplicity/selection.py:295
#, python-format
msgid ""
"Fatal Error: The file specification\n"
"    %s\n"
"cannot match any files in the base directory\n"
"    %s\n"
"Useful file specifications begin with the base directory or some\n"
"pattern (such as '**') which matches the base directory."
msgstr ""

#: ../duplicity/selection.py:304
#, python-format
msgid ""
"Fatal Error while processing expression\n"
"%s"
msgstr ""

#: ../duplicity/selection.py:313
#, python-format
msgid ""
"Last selection expression:\n"
"    %s\n"
"only specifies that files be included.  Because the default is to\n"
"include all files, the expression is redundant.  Exiting because this\n"
"probably isn't what you meant."
msgstr ""

#: ../duplicity/selection.py:369
#, python-format
msgid "Reading globbing filelist %s"
msgstr ""

#: ../duplicity/selection.py:402
#, python-format
msgid "Error compiling regular expression %s"
msgstr "Produciuse un erro ao compilar a expresión regular %s"

#: ../duplicity/selection.py:419
msgid ""
"Warning: exclude-device-files is not the first selector.\n"
"This may not be what you intended"
msgstr ""

#: ../duplicity/tempdir.py:135
#, python-format
msgid "Using temporary directory %s"
msgstr ""

#: ../duplicity/tempdir.py:179
#, python-format
msgid "Registering (mktemp) temporary file %s"
msgstr ""

#: ../duplicity/tempdir.py:201
#, python-format
msgid "Registering (mkstemp) temporary file %s"
msgstr ""

#: ../duplicity/tempdir.py:233
#, python-format
msgid "Forgetting temporary file %s"
msgstr ""

#: ../duplicity/tempdir.py:236
#, python-format
msgid "Attempt to forget unknown tempfile %s - this is probably a bug."
msgstr ""

#: ../duplicity/tempdir.py:255
#, python-format
msgid "Removing still remembered temporary file %s"
msgstr ""

#: ../duplicity/tempdir.py:258
#, python-format
msgid "Cleanup of temporary file %s failed"
msgstr ""

#: ../duplicity/tempdir.py:263
#, python-format
msgid "Cleanup of temporary directory %s failed - this is probably a bug."
msgstr ""

#: ../duplicity/util.py:138
#, python-format
msgid "IGNORED_ERROR: Warning: ignoring error as requested: %s: %s"
msgstr ""

#: ../duplicity/util.py:205
#, python-format
msgid "Releasing lockfile %s"
msgstr ""
